### ISSUE TITLE
Disallow 32-bit sims in run configurations with Arch set to 64-bit

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-idea#20]
DeviceType.getBestDeviceType() has the logic implemented already, need to wire it up with the UI.

**Comment by magicgoose** [comment]
Yeah, this is certainly needed as it would reduce the amount of confusion for iOS noobs like me. (Just tried to launch an app on iPhone 4s / 64-bit and, of course, it didn't work out :laughing: )
