### ISSUE TITLE
License manager messes up the color scheme

### ISSUE THREAD

**Issue by AgrarPirat** [robovm/robovm-idea#47]
Opening the roboVM license manager while using the dark color scheme messes up the the background colors of the Android Studio UI. Here's a example:
![screen shot 2015-04-22 at 9 55 31 am](https://cloud.githubusercontent.com/assets/8950110/7269743/cc5404f8-e8d6-11e4-8abd-40d63d4c70f2.png)

Happens with versions:
org.robovm.idea-1.1.1-SNAPSHOT-plugin-dist-20150422_021132-51.jar
Android Studio 1.1.0 (havn't tried the latest version of AS)

**Comment by badlogic** [comment]
Fixed in the next nightly.
