### ISSUE TITLE
RoboVM Icon improvements

### ISSUE THREAD

**Issue by ajhager** [robovm/robovm-idea#50]
- [ ] Add 2x version of icons for retina screens.
- [ ] Android modules use a custom icon on the module folder. Add a `ProjectViewNodeDecorator` subclass with a custom folder/module icon for RoboVM modules in a multi module projects.

``` xml
<projectViewNodeDecorator id="robovm.module.node.decorator" implementation="org.robovm.tools.idea.ModuleNodeIconDecorator"/>
```

**Comment by badlogic** [comment]
Moved this over to the idea plugin tracker.
