### ISSUE TITLE
Can't select simulator with iOS 7 in run/debug configuration

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm-idea#51]
I have installed both iOS 8.3 and 7.1 simulators, but in RoboVM run/debug configuration there is no way to select iOS 7.1, there's only iOS 8.3.

I did write

```
    <key>MinimumOSVersion</key>
    <string>7.0</string>
```

in the `Info.plist.xml`, though. And I couldn't find anything else which could prevent me from running on iOS 7.

**Comment by nazargulov** [comment]
the same problem.

**Comment by badlogic** [comment]
Can you select iOS 7 Sims from within Xcode when creating a plain ObjC iOS
Xcode project?

**Comment by magicgoose** [comment]
@badlogic in XCode (6.3.x) there's no way to see and select the iOS simulator version for running (thanks Apple) — but I also have Xamarin Studio and it can do this. And of course I have installed iOS 7 sims:
![screen shot 2015-04-30 at 12 27 05 pm](https://cloud.githubusercontent.com/assets/1442206/7410429/6f9eb5e8-ef37-11e4-8c73-10c93e99e0cb.png)

**Comment by ntherning** [comment]
We have an issue for this in the main repo: robovm/robovm#943.
