### ISSUE TITLE
Cross Platform template wizard

### ISSUE THREAD

**Issue by ajhager** [robovm/robovm-idea#53]
There are some changes that are needed to make the RoboVM part play nice as a module. It would be nice to also have an option of creating a RoboVM module in an existing (Android) project, that has those changes as well.

**Comment by ItsHarper** [comment]
Is this likely to actually happen for 1.5, or does it look like it's going to get pushed back again?

**Comment by badlogic** [comment]
This is going to happen for 1.5 :)

**Comment by ItsHarper** [comment]
That is amazing to hear. Is there going to be a preview release I can use beforehand? Doing everything manually continues to give me problems.
