### ISSUE TITLE
RoboVM IDEA plugin 1.2 broken

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-idea#56]
See https://twitter.com/nivrig/status/596223407445962753

**Comment by ntherning** [comment]
Just tried with "None" as build system and that works as expected at least. Maybe he's using Gradle/Maven? I'm on 14.1.1.

**Comment by badlogic** [comment]
Can't reproduce. Procedure:
1. Delete ~/.robovm-sdks
2. Delete RoboVM plugin from IDEA, restart
3. Install RoboVM IDEA plugin 1.2.0 via JetBrains repository
4. Import robovm-samples via Gradle
5. Compile, run, debug a few samples.
6. Close project, create new single view project using Gradle/Maven, compile, run, debug

All of that seems to work.
