### ISSUE TITLE
Won't take license key

### ISSUE THREAD

**Issue by cypherdare** [robovm/robovm-idea#59]
When I tried entering the license key, hitting enter did nothing visibly. The blank all-zeros number was still on screen even after hitting the Refresh button. I closed and reopened the license manager a couple times with no success yesterday, but when I reopened it today, the key was already there. I can't remember if I restarted IDEA prior to it working.

**Comment by badlogic** [comment]
Reproduction steps, IDEA or Eclipse, with a key already set:
1. Open License Manager GUI
2. Enter valid license key, wait for it to be accepted
3. Close it
4. Open and close the license manager GUI 4-5 times

After step 4, the license key will not be displayed anymore and entering a new license key doesn't work either. Restarting the IDE fixes it.

**Comment by badlogic** [comment]
Fixed i license manager code. Fix will be available in the next snapshot build which you can find under http://downloads.robovm.com.

Thanks for reporting!
