### ISSUE TITLE
Java 6 version

### ISSUE THREAD

**Issue by Arcnor** [robovm/robovm-idea#61]
I know you'd probably be against this, but hopefully you at least will entertain the idea :)

Currently, I'm (and a lot of other people too, I'm sure) using Java 6 to run IDEA on OSX, because font rendering with Oracle Java is simply awful, and the custom JDK JetBrains provides to try to fix this still doesn't work properly (colors are off and scrolling performance is very bad for some reason).

So, can you compile this IDEA plugin as Java 6? Obviously right now, when trying to run IDEA with it installed, it just crashes IDEA for me with an error about the class version.

**Comment by badlogic** [comment]
The plugin itself can actually run on Java 6, the compiler and other
related bits can't. We could try to recompile via RetroLambda, but that's
currently not a high-priority i'm afraid. I'll leave this open for now and
will update you once we have the time to give RetroLambda a try.

**Comment by Arcnor** [comment]
I meant only the plugin, yeah. I don't think it's necessary to make the
rest of RoboVM run on any other than the last version of Java :)

Right now it doesn't work, because the plugin has been compiled to Java 7.
I checked the code and there is only a few places where Java 7 code
(diamond operator and multi try catch) it's used

**Comment by badlogic** [comment]
I'm afraid the compiler also needs to be Java 6 compatible since we
directly call into it from within the plugin. There's no way around that
other than making the compiler Java 6 compatible as well.

**Comment by Arcnor** [comment]
Oh, so the compiler is running on the same JVM as the plugin & IDEA?

Well, I guess that makes integration easier, but it will make IDEA unstable if the compiler throws an OOME (and that happens a lot for me, although less and less after 1.1/1.2). What IDEA does is running compilers on another JVM using some utility classes from IDEA, and that allows me to run Java 7 / 8 / 9 for my projects as well.

I'm sure you knew that already, but just in case :).

Anyway, I know that's not something you guys are planning to change, but maybe is something to take into account.

Thank you!

**Comment by badlogic** [comment]
Oh, we might change it, just not at the moment. But JetBrains will likely
have to fix the Java 7 issues very soon, since Apple no longer updates
their Java 6 and will likely remove it soonish.

As for a OOMs: what's your VM heap setting for IDEA?

**Comment by Arcnor** [comment]
Well, they've been trying for a while, and have something that works, just not that well. I'm assuming they'll stop supporting OSX with J6 and that's it, although that's not a good prospect for us...

My VM settings are the default on some computers, and something like 4Gb on my work computers. Is not a real issue for me (although IDEA already consumes a lot of memory :smile:) but I was just talking generally.

**Comment by badlogic** [comment]
I'm closing this out now as we won't backport to Java 6.
