### ISSUE TITLE
Error when adding a RoboVM module to a project

### ISSUE THREAD

**Issue by ajhager** [robovm/robovm-idea#66]
## New Module

_Error adding module to project: Parameter 'directory' is not a directory._

It doesn't seem to affect anything, but is bad for user experience.

**Comment by badlogic** [comment]
If possible, please always post the full stack trace.

Overlooked this, i should have fixed it for 1.3 :/

**Comment by badlogic** [comment]
Couldn't reproduce this one.

**Comment by ajhager** [comment]
Sorry, It wasn't a stack trace. It is a small IntelliJ popup. I just started seeing in a snapshot build of the idea plugin (I think.) I will debug this on my machine.

**Comment by badlogic** [comment]
This should be fixed.
